# config file version
apiVersion: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: DubHLik4k
    url: http://prometheus:9090
    editable: true